-- Types
DROP TYPE IF EXISTS job_status CASCADE;
CREATE TYPE job_status AS ENUM ('queued', 'running', 'succeeded', 'failed');

-- 1. Jobs
-- Stores the state of asynchronous processing tasks (SRT -> Analysis).
CREATE TABLE IF NOT EXISTS jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID, -- Nullable for now as not currently populated by SBJobsIO
    input_path TEXT NOT NULL,
    output_path TEXT,
    params JSONB DEFAULT '{}'::jsonb,
    status job_status NOT NULL DEFAULT 'queued',
    progress INTEGER DEFAULT 0,
    error TEXT,
    
    -- Timestamps match usage in SBJobsIO
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE,
    started_at TIMESTAMP WITH TIME ZONE,
    finished_at TIMESTAMP WITH TIME ZONE
);

-- 2. Cache for translations
-- Shared look-up table for translations to save costs/time.
CREATE TABLE IF NOT EXISTS cached_translations (
    id TEXT PRIMARY KEY, -- Matches CacheEntry.id (SHA hash)
    form_org_lang TEXT NOT NULL,
    sentence_org_lang TEXT NOT NULL,
    word_target_lang TEXT,
    sentence_target_lang TEXT,
    org_lang TEXT,
    target_lang TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Decks
-- A deck is a specific configuration of cards generated from an Analyzed Job.
CREATE TABLE IF NOT EXISTS decks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id UUID REFERENCES jobs(id), -- Logical link to the content (generated by the Job)
    user_id UUID, -- Nullable for now as not currently populated by SBJobsIO
    build_version TEXT,
    
    -- Store the full request so we can reproduce/debug
    request_params JSONB NOT NULL,
    
    -- Metadata about the result
    card_count INTEGER,
    achieved_coverage FLOAT,
    stopped_reason TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Cards
-- Individual flashcards belonging to a deck.
CREATE TABLE IF NOT EXISTS cards (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    deck_id UUID REFERENCES decks(id), -- FK to Decks
    
    -- Core Content
    lemma TEXT NOT NULL,
    pos TEXT,
    prompt TEXT NOT NULL,
    answer TEXT NOT NULL,
    sentence TEXT,
    sentence_translation TEXT,
    
    -- Meta / Indexing
    source_lang_tag TEXT,
    target_lang_tag TEXT,
    analyzed_hash TEXT, -- Denormalized for easier querying
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
